exclude:
  - README.md
  - .gitignore
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:categories/:title
baseurl: 

#prose
prose:
  rooturl: "_posts"
  media: "assets"
  metadata:
    _posts/shows:
      - name: "layout"
        field:
          element: "hidden"
          value: "show"
      - name: "name"
        field:
          element: "text"
          label: "Show Name"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
      - name: "categories"
        field:
          element: "select"
          label: "Select a series"
          options:
            - name: "footsteps"
              value: "footsteps"
            - name: "mechaniques"
              value: "mechaniques"
            - name: "tactile"
              value: "tactile"
            - name: "hybrids"
              value: "hybrids"
      - name: "flickr"
        field:
          element: "text"
          label: "Flickr Photoset ID"
          value: ""
      - name: "vimeo"
        field:
          element: "text"
          label: "Vimeo Video ID"
          value: ""
      - name: "collaborators"
        field:
          element: "textarea"
          label: "Artistic Collaborators"
          value: ""
      - name: "voices"
        field:
          element: "textarea"
          label: "Voices by"
          value: ""
      - name: "performers"
        field:
          element: "textarea"
          label: "Performers"
          value: ""
      - name: "thanks"
        field:
          element: "textarea"
          label: "Many Thanks To"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          options:
            - name: "instructions"
              value: "instructions"
            - name: "archive"
              value: "archive"
            - name: "current"
              value: "current"
    _posts/series:
      - name: "layout"
        field:
          element: "hidden"
          value: "series"
    _posts/instructions:
      - name: "categories"
        field:
          element: "hidden"
          value: "instructions"
    _posts/archive:
      - name: "categories"
        field:
          element: "hidden"
          value: "archive"
    _posts/featured:
      - name: "categories"
        field:
          element: "hidden"
          value: "featured"
    _posts/current:
      - name: "categories"
        field:
          element: "hidden"
          value: "current"
      - name: "map"
        field:
          element: "text"
          label: "Map Id"
          value: ""
      - name: "image"
        field:
          element: "image"
          label: "Image url"
          value: ""
      - name: "tags"
        field:
          element: "select"
          label: "If there is an image, select the image tag"
          options:
            - name: "image"
              value: "image"
