exclude:
  - README.md
  - .gitignore
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:categories/:title
baseurl: /

#prose
prose:
  media: 'assets'
  rooturl: "_posts"
  metadata:
    _posts/shows:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
      - name: "categories"
        field:
          element: "select"
          label: "Select a series"
          placeholder: "Default"
          options:
            - name: "footsteps"
              value: "footsteps"
            - name: "mechaniques"
              value: "mechaniques"
            - name: "tactile"
              value: "tactile"
            - name: "wildcard"
              value: "wildcard"
